// Mocks generated by Mockito 5.4.2 from annotations
// in movie_app/test/features/content/data/repository/tvshows/tvshow_local_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/features/content/data/datasources/tvshows/tvshows_local_data_source.dart'
    as _i3;
import 'package:movie_app/features/content/domain/entities/tvshows_entity.dart'
    as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TVShowsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVShowsLocalDataSource extends _i1.Mock
    implements _i3.TVShowsLocalDataSource {
  @override
  _i2.SharedPreferences get preferences => (super.noSuchMethod(
        Invocation.getter(#preferences),
        returnValue: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#preferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_0(
          this,
          Invocation.getter(#preferences),
        ),
      ) as _i2.SharedPreferences);
  @override
  _i4.Future<bool> storeTVShows(List<_i5.TVShowsEntity>? tvShows) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeTVShows,
          [tvShows],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  List<_i5.TVShowsEntity> getLocalTVShows() => (super.noSuchMethod(
        Invocation.method(
          #getLocalTVShows,
          [],
        ),
        returnValue: <_i5.TVShowsEntity>[],
        returnValueForMissingStub: <_i5.TVShowsEntity>[],
      ) as List<_i5.TVShowsEntity>);
}
