// Mocks generated by Mockito 5.4.2 from annotations
// in movie_app/test/features/content/data/datasource/tvshows/tvshow_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/features/content/data/datasources/tvshows/tvshows_remote_data_source.dart'
    as _i2;
import 'package:movie_app/features/content/domain/entities/tvshows_entity.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TVShowsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVShowsRemoteDataSource extends _i1.Mock
    implements _i2.TVShowsRemoteDataSource {
  @override
  _i3.Future<List<_i4.TVShowsEntity>> getTVShows() => (super.noSuchMethod(
        Invocation.method(
          #getTVShows,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.TVShowsEntity>>.value(<_i4.TVShowsEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TVShowsEntity>>.value(<_i4.TVShowsEntity>[]),
      ) as _i3.Future<List<_i4.TVShowsEntity>>);
  @override
  _i3.Future<List<_i4.TVShowsEntity>> searchTVShows(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTVShows,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i4.TVShowsEntity>>.value(<_i4.TVShowsEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TVShowsEntity>>.value(<_i4.TVShowsEntity>[]),
      ) as _i3.Future<List<_i4.TVShowsEntity>>);
}
