// Mocks generated by Mockito 5.4.2 from annotations
// in movie_app/test/features/detail/data/repository/tvshows/tvshow_detail_remote_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/core/http_service.dart' as _i2;
import 'package:movie_app/features/detail/data/datasources/tvshow/tvshow_detail_remote_data_source.dart'
    as _i3;
import 'package:movie_app/features/detail/domain/entities/tv_show_detail_entity.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpService_0 extends _i1.SmartFake implements _i2.HttpService {
  _FakeHttpService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TVShowDetailRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVShowDetailRemoteDataSource extends _i1.Mock
    implements _i3.TVShowDetailRemoteDataSource {
  @override
  _i2.HttpService get httpService => (super.noSuchMethod(
        Invocation.getter(#httpService),
        returnValue: _FakeHttpService_0(
          this,
          Invocation.getter(#httpService),
        ),
        returnValueForMissingStub: _FakeHttpService_0(
          this,
          Invocation.getter(#httpService),
        ),
      ) as _i2.HttpService);
  @override
  _i4.Future<_i5.TVShowDetailEntity?> getTVShowDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTVShowDetail,
          [id],
        ),
        returnValue: _i4.Future<_i5.TVShowDetailEntity?>.value(),
        returnValueForMissingStub: _i4.Future<_i5.TVShowDetailEntity?>.value(),
      ) as _i4.Future<_i5.TVShowDetailEntity?>);
}
