// Mocks generated by Mockito 5.4.2 from annotations
// in movie_app/test/features/detail/data/repository/tvshows/tvshow_detail_local_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app/features/detail/data/datasources/tvshow/tvshow_detail_local_data_source.dart'
    as _i2;
import 'package:movie_app/features/detail/domain/entities/tv_show_detail_entity.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TVShowDetailLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVShowDetailLocalDataSource extends _i1.Mock
    implements _i2.TVShowDetailLocalDataSource {
  @override
  _i3.Future<bool> storeTVShowDetail(_i4.TVShowDetailEntity? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeTVShowDetail,
          [entity],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<_i4.TVShowDetailEntity?> getLocalTVShowDetail(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalTVShowDetail,
          [id],
        ),
        returnValue: _i3.Future<_i4.TVShowDetailEntity?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.TVShowDetailEntity?>.value(),
      ) as _i3.Future<_i4.TVShowDetailEntity?>);
}
